### ISSUE TITLE
Review Original List of Prototype User Stories

### ISSUE THREAD

**Issue by klappy** [Bridgeconn/translationManager#45]
List user stories for Prototype, and review with team.

**Comment by binu-alexander** [comment]
MTT
Translator
View Assigned work (only in tS/tC)
View assigned tasks in their Editor


Submit progress data against assigned work


View list of submitted work with preview


See their progress, remaining in assignment
Know what I’m suppose to translate
Team Leader
Lead Translator
Team Assigned work
Translator/Responsible for team/peer checking


Language Project Manager
Project Management
Teams
Define settings, team size, chapters/books, project type (new or revision), dynamic or literal, project plan


Assign the books, chapters to teams.


Allow permissions to edit after MTT marks chunk as done.


Identify, set, configure targets for chapters, books in each stage based on assignment.


Calculate per person output.


View number of verses, chapters, books in each stage (completed, remaining for each stage)


Track progress and status reports from translationCore
Ensuring team meets their target and objectives


Identify bottlenecks and possible solutions

**Comment by klappy** [comment]
**MTT Translator**

1. View Assigned work (only in tS/tC)
2. Submit progress data against assigned work
3. See their progress, remaining in assignment
4. Know what I’m suppose to translate

**Team Leader**

1. Lead Translator
2. Team Assigned work
3. Translator/Responsible for team/peer checking

**Language Project Manager**

1. Manage Project
2. Manage Teams
3. Assign the books, chapters to teams.
4. Identify, set, configure target dates for chapters, books in each stage based on assignment.
5. View number of verses, chapters, books in each stage (completed, remaining for each stage)
6. Track progress and status reports from translationCore
7. Ensuring team meets their target and objectives
